#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Wed Nov  5 12:41:45 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((211, 461))
        self.SetTitle("inicio de seion-CinePlus")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("D:\\CineplusJeraldine3A\\Logotipo.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(10, 79, 255))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        lbTitulo = wx.StaticText(self.panel_1, wx.ID_ANY, "Bienvenido(a) a CinePlus", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbTitulo.SetMinSize((132, 35))
        lbTitulo.SetForegroundColour(wx.Colour(0, 0, 0))
        lbTitulo.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbTitulo, 0, wx.EXPAND, 0)

        lbLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("Logotipo.jpg", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(lbLogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbUsuario.SetMinSize((445, 20))
        lbUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbClave = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contraseña:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbClave.SetMinSize((445, 20))
        lbClave.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbClave, 0, 0, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        self.tfClave.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnEntrar = wx.Button(self.panel_1, wx.ID_ANY, "Entrar")
        self.btnEntrar.SetMinSize((120, 35))
        self.btnEntrar.SetBackgroundColour(wx.Colour(29, 236, 37))
        self.btnEntrar.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.btnEntrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        self.btnSalir.SetMinSize((120, 35))
        self.btnSalir.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btnSalir.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnEntrar.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: ventana1.<event_handler>
        nombre = self.tfUsuario.GetValue ()
        clave = self.tfClave.GetValue ()

        if nombre == "Jeraldine" and clave == "123":
            print(f"¡Bienvenida, {nombre}!Acceso autorizado.")
            v2= ventana2(self)
            v2.Show()
            self.Hide()

        else:
            print("Acceso denegado. Usuario o clave incorrectos.")

        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: ventana1.<event_handler>
        print("Event handler 'cerrar_programa' not implemented!")
        event.Skip()

# end of class ventana1

class ventana2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((538, 507))
        self.SetTitle("Taquilla-CinePlus-")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("D:\\CineplusJeraldine3A\\taquillas.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(226, 53, 255))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("taquillas.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        label_1.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("taquillas.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Película:")
        label_2.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_2, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        label_3.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_3, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        label_4.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_4, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.cmbPelicula = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Megan 2.0", u"Mufasa:El rey león", "Las guerreras K-pop"], style=wx.CB_DROPDOWN)
        self.cmbPelicula.SetMinSize((120, 30))
        grid_sizer_4.Add(self.cmbPelicula, 0, 0, 0)

        self.lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "----")
        self.lbSala.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_4.Add(self.lbSala, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_5.Add(self.rbHorario1, 0, 0, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_5.Add(self.rbHorario2, 0, 0, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_5.Add(self.rbHorario3, 0, 0, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_5.Add(self.panel_2, 1, wx.EXPAND, 0)

        self.bmPelicula = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:\\CineplusJeraldine3A\\Pelicula2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(self.bmPelicula, 0, wx.ALIGN_RIGHT, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos")
        label_6.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(label_6, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_6 = wx.GridSizer(2, 2, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos $(80):")
        label_7.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_6.Add(label_7, 0, 0, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "",style=wx.TE_PROCESS_ENTER)
        self.tfAdultos.SetMinSize((110, 23))
        self.tfAdultos.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_6.Add(self.tfAdultos, 0, 0, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores $ (70):")
        label_8.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_6.Add(label_8, 0, 0, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "",style=wx.TE_PROCESS_ENTER)
        self.tfMenores.SetMinSize((110, 23))
        self.tfMenores.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_6.Add(self.tfMenores, 0, 0, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal: $")
        self.lbSubtotal.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.lbSubtotal, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetMinSize((170, 54))
        self.btnLimpiar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        self.btnLimpiar.SetBitmap(wx.Bitmap("D:\\CineplusJeraldine3A\\limpiarboton.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_7.Add(self.btnLimpiar, 0, 0, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetMinSize((170, 54))
        self.btnSiguiente.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        self.btnSiguiente.SetBitmap(wx.Bitmap("D:\\CineplusJeraldine3A\\siguienteboton.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_7.Add(self.btnSiguiente, 0, wx.ALIGN_RIGHT, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cmbPelicula.Bind(wx.EVT_COMBOBOX, self.seleccionPelicula)
        self.rbHorario1.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario1)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.tfAdultos.Bind(wx.EVT_TEXT_ENTER, self.sumarAdultos)
        self.tfMenores.Bind(wx.EVT_TEXT_ENTER, self.sumarMenores)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        # end wxGlade

    def cargar_imagen(self,ruta):
        #print(f"ruta: {ruta}")
        bitmap=wx.Bitmap(ruta,wx.BITMAP_TYPE_ANY)
        self.bmPelicula.SetBitmap(bitmap)

    def seleccionPelicula(self, event):  # wxGlade: ventana2.<event_handler>
         pelicula=self.cmbPelicula.GetValue()
         imagen=""
         sala=""
         horario1=horario2=horario3=""
        
         print(f"Pelicula seleccionada: {pelicula}")

         if pelicula == "Mufasa:El rey león":
           imagen="Pelicula1.png"
           sala="1"
           horario1="14:00"
           horario2="17:00"
           horario3="20:00"

         elif pelicula == "Las guerreras K-pop":
            imagen="Pelicula2.png"
            sala="2"
            horario1="13:30"
            horario2="16:30"
            horario3="19:30"
        
         elif pelicula == "Megan 2.0":
            imagen="Pelicula3.png"
            sala="3"
            horario1="15:00"
            horario2="18:00"
            horario3="21:00"

         self.cargar_imagen(imagen)
         self.lbSala.SetLabel(sala)
         self.rbHorario1.SetLabel(horario1)
         self.rbHorario2.SetLabel(horario2)
         self.rbHorario3.SetLabel(horario3)
         self.informacion=f"Pelicula:{pelicula} \n Sala:{sala}"
         print(f"Listo paran disfrutar de \n {self.informacion}")
         event.Skip()

    def seleccionHorario1(self, event):  # wxGlade: ventana2.<event_handler>
        print("Event handler 'seleccionHorario1' not implemented!")
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: ventana2.<event_handler>
        print("Event handler 'seleccionHorario2' not implemented!")
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: ventana2.<event_handler>
        print("Event handler 'seleccionHorario3' not implemented!")
        event.Skip()

    def sumarAdultos(self, event):  # wxGlade: ventana2.<event_handler>
        print("Event handler 'sumarAdultos' not implemented!")
        event.Skip()

    def sumarMenores(self, event):  # wxGlade: ventana2.<event_handler>
        print("Event handler 'sumarMenores' not implemented!")
        event.Skip()

    def limpiarTaquilla(self, event):  # wxGlade: ventana2.<event_handler>
        print("Event handler 'limpiarTaquilla' not implemented!")
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: ventana2.<event_handler>
        print("Event handler 'siguienteVentana' not implemented!")
        event.Skip()

# end of class ventana2

class ventana3(wx.Frame):
    def __init__(self, parent, informacion="",subtotal=0):
        # begin wxGlade: ventana3.__init__
        super()._init_(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((703, 730))
        self.SetTitle("frame_2")
        print(f"Datos de la ventana 2:\n Informacion: {informacion} \n")
        print(f"subtotal: {subtotal}")


        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetMinSize((117, 44))
        self.panel_1.SetBackgroundColour(wx.Colour(219, 112, 147))
        
        #Variables de instancias ventana 3
        self.infoDulceria=""
        self.subtotalDulceria=0

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("D:\\CineplusJeraldine3A\\dulceria.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulceria")
        label_7.SetFont(wx.Font(16, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Elephant"))
        grid_sizer_1.Add(label_7, 0, wx.ALIGN_CENTER, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./dulceria.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_4, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_6 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        self.spComboB = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spComboB.SetMinSize((46, 23))
        grid_sizer_6.Add(self.spComboB, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_7 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_6.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Basico $75")
        label_1.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_7.Add(label_1, 0, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas Ch")
        grid_sizer_7.Add(label_2, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refresco Ch")
        grid_sizer_7.Add(label_3, 0, 0, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./basico.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_6.Add(bitmap_2, 0, wx.EXPAND, 0)

        grid_sizer_8 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        self.spComboC = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_8.Add(self.spComboC, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_9 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_8.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cuates $130")
        label_4.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_9.Add(label_4, 0, wx.ALIGN_CENTER, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas Md")
        grid_sizer_9.Add(label_5, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "2 Refrescos Md")
        grid_sizer_9.Add(label_6, 0, 0, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./combo cuates.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_8.Add(bitmap_3, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        grid_sizer_10 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_3.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        self.spComboF = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_10.Add(self.spComboF, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_11 = wx.FlexGridSizer(4, 1, 0, 0)
        grid_sizer_10.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Familiar $180")
        label_8.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_11.Add(label_8, 0, 0, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas G")
        grid_sizer_11.Add(label_9, 0, 0, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "3 Refescos G")
        grid_sizer_11.Add(label_10, 0, 0, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "1 Dulce")
        grid_sizer_11.Add(label_11, 0, 0, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./familiar.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_10.Add(bitmap_5, 0, wx.ALIGN_RIGHT, 0)

        self.panel_5 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_3.Add(self.panel_5, 1, wx.EXPAND, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        grid_sizer_12 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_4.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./palomitas.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_12.Add(bitmap_6, 0, 0, 0)

        grid_sizer_14 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_12.Add(grid_sizer_14, 1, wx.EXPAND, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas $45")
        label_12.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_14.Add(label_12, 0, 0, 0)

        grid_sizer_15 = wx.GridSizer(3, 2, 0, 0)
        grid_sizer_14.Add(grid_sizer_15, 1, wx.EXPAND, 0)

        self.spPaliomitasCh = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_15.Add(self.spPaliomitasCh, 0, wx.ALIGN_RIGHT, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas ")
        label_13.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_15.Add(label_13, 0, 0, 0)

        self.spPalomitasMd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_15.Add(self.spPalomitasMd, 0, wx.ALIGN_RIGHT, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Medianas ")
        label_14.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_15.Add(label_14, 1, 0, 0)

        self.spPalomitasG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_15.Add(self.spPalomitasG, 0, wx.ALIGN_RIGHT, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes ")
        label_15.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_15.Add(label_15, 0, wx.EXPAND, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_12.Add(self.panel_2, 1, wx.EXPAND, 0)

        grid_sizer_16 = wx.GridSizer(1, 5, 0, 0)
        grid_sizer_4.Add(grid_sizer_16, 1, wx.EXPAND, 0)

        bitmap_7 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./refresco.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_16.Add(bitmap_7, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_18 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_16.Add(grid_sizer_18, 1, wx.EXPAND, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refrescos")
        label_17.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_18.Add(label_17, 0, 0, 0)

        label_18 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Tamaño")
        label_18.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_18.Add(label_18, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.cmbTamano = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        grid_sizer_18.Add(self.cmbTamano, 0, 0, 0)

        grid_sizer_19 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_16.Add(grid_sizer_19, 1, wx.EXPAND, 0)

        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_19.Add(self.panel_3, 1, wx.EXPAND, 0)

        label_19 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sabor")
        label_19.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_19.Add(label_19, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.cmbsabor = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        grid_sizer_19.Add(self.cmbsabor, 0, 0, 0)

        grid_sizer_20 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_16.Add(grid_sizer_20, 1, wx.EXPAND, 0)

        self.panel_4 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_4.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_20.Add(self.panel_4, 1, wx.EXPAND, 0)

        label_20 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad")
        label_20.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        grid_sizer_20.Add(label_20, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT, 0)

        self.spCantidad = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_20.Add(self.spCantidad, 0, 0, 0)

        grid_sizer_21 = wx.FlexGridSizer(1, 1, 0, 0)
        grid_sizer_16.Add(grid_sizer_21, 1, wx.EXPAND, 0)

        self.btnAgregar = wx.Button(self.panel_1, wx.ID_ANY, "Agregar")
        self.btnAgregar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_21.Add(self.btnAgregar, 0, 0, 0)

        grid_sizer_22 = wx.GridSizer(1, 4, 0, 0)
        sizer_1.Add(grid_sizer_22, 1, wx.EXPAND, 0)

        self.lbProductosAgregados = wx.StaticText(self.panel_1, wx.ID_ANY, "Productos Agregados:")
        self.lbProductosAgregados.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_22.Add(self.lbProductosAgregados, 0, wx.ALIGN_CENTER, 0)

        label_22 = wx.StaticText(self.panel_1, wx.ID_ANY, "-----")
        label_22.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_22.Add(label_22, 0, wx.ALIGN_CENTER, 0)

        label_23 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal Dulceria ")
        label_23.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_22.Add(label_23, 0, wx.ALIGN_CENTER, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "$00.00")
        self.lbSubtotal.SetForegroundColour(wx.Colour(255, 0, 0))
        self.lbSubtotal.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Segoe UI"))
        grid_sizer_22.Add(self.lbSubtotal, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar\n")
        self.btnLimpiar.SetMinSize((130, 58))
        self.btnLimpiar.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        self.btnLimpiar.SetBitmap(wx.Bitmap("D:\\CineplusJeraldine3A\\limpiarboton.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_5.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente\n")
        self.btnSiguiente.SetMinSize((119, 58))
        self.btnSiguiente.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        self.btnSiguiente.SetBitmap(wx.Bitmap("D:\\CineplusJeraldine3A\\siguienteboton.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_5.Add(self.btnSiguiente, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_21.AddGrowableRow(0)

        grid_sizer_20.AddGrowableRow(1)

        grid_sizer_19.AddGrowableRow(1)

        grid_sizer_18.AddGrowableRow(1)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spComboC.Bind(wx.EVT_SPINCTRL, self.calcularComboCuates)
        self.spComboF.Bind(wx.EVT_SPINCTRL, self.calcularComboFamiliar)
        self.spPaliomitasCh.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasCh)
        self.spPalomitasMd.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasMd)
        self.spPalomitasG.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasG)
        self.btnAgregar.Bind(wx.EVT_BUTTON, self.agregarRefrescos)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarDulceria)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteDulceria)
        # end wxGlade

    def calcularComboCuates(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboC.GetValue())
        subtotalcombo=numero*130
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Cuates \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularComboFamiliar(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboF.GetValue())
        subtotalcombo=numero*180
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Familiar \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularPalomitasCh(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spPaliomitasCh.GetValue())
        subtotalcombo=numero*25
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas Chicas \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularPalomitasMd(self, event):  # wxGlade: ventana3.<event_handler>
         numero=int(self.spPalomitasMd.GetValue())
         subtotalcombo=numero*40
         self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
         self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
         self.infoDulceria=self.infoDulceria + f"{numero} Palomitas Medianas \n"
         self.lbProductosAgregados.SetLabel(self.infoDulceria)
         event.Skip()

    def calcularPalomitasG(self, event):  # wxGlade: ventana3.<event_handler>
         numero=int(self.spPalomitasG.GetValue())
         subtotalcombo=numero*60
         self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
         self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
         self.infoDulceria=self.infoDulceria + f"{numero} Palomitas Grandes \n"
         self.lbProductosAgregados.SetLabel(self.infoDulceria)
         event.Skip()

    def agregarRefrescos(self, event):  # wxGlade: ventana3.<event_handler>
        
        numero=int(self.spCantidad.GetValue())
        tamanyo=self.cmbTamano.GetValue()
        sabor=self.cmbsabor.GetValue()
        if tamanyo == "CHICO":
            subtotalrefresco=numero*25
        elif tamanyo == "MEDIANO":
            subtotalrefresco=numero*40
        elif tamanyo == "GRANDE":
            subtotalrefresco=numero*60

        self.subtotalDulceria=self.subtotalDulceria+subtotalrefresco
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")

        self.infoDulceria=self.infoDulceria + f"{numero} refresco: {sabor} tamaño {tamanyo} \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)

        event.Skip()

    def limpiarDulceria(self, event):  # wxGlade: ventana3.<event_handler>

        #Limpiamos los de instancias
        self.subtotalDulceria=0
        self.infoDulceria=0

        #Limpiamos los controles
        self.spComboB.SetValue(0)
        self.spComboC.SetValue(0)
        self.spComboF.SetValue(0)
        self.spPaliomitasCh.SetValue(0)
        self.spPalomitasMd.SetValue(0)
        self.spPalomitasG.SetValue(0)
        self.spCantidad.SetValue(0)
        self.cmbsabor.SetSelection(wx.NOT_FOUND)
        self.cmbTamano.SetSelection(wx.NOT_FOUND)
        self.lbProductosAgregados.SetLabel("-----")
        self.lbSubtotal.SetLabel("$00.00")

    def limpiarDulceria(self, event):  # wxGlade: ventana3.<event_handler>
        event.Skip()

    def siguienteDulceria(self, event):  # wxGlade: ventana3.<event_handler>
        print("Event handler 'siguienteDulceria' not implemented!")
        event.Skip()

# end of class ventana3

class MyAppCinePlus(wx.App):
    def OnInit(self):
        self.frame_2 = ventana3(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame_2)
        self.frame_2.Show()
        return True

# end of class MyAppCinePlus

if __name__ == "__main__":
    appCinePlus = MyAppCinePlus(0)
    appCinePlus.MainLoop()
