#!/usr/bin/env python3
# -*- coding: CP1252 -*-
#
# generated by wxGlade 1.1.1 on Wed Oct 22 13:15:03 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((472, 457))
        self.SetTitle("Inicio de seccion -CinePlus")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("D:\\CineplusJeraldine3A\\Logotipo.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(0, 255, 255))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        Ibbienvenido = wx.StaticText(self.panel_1, wx.ID_ANY, "Bienvenido a CinePlus", style=wx.ALIGN_CENTER_HORIZONTAL)
        Ibbienvenido.SetMinSize((132, 35))
        Ibbienvenido.SetBackgroundColour(wx.Colour(0, 255, 255))
        Ibbienvenido.SetForegroundColour(wx.Colour(46, 141, 188))
        Ibbienvenido.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(Ibbienvenido, 0, wx.EXPAND, 0)

        IbLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./Logotipo.jpg", wx.BITMAP_TYPE_ANY))
        IbLogo.SetMinSize((170, 171))
        sizer_1.Add(IbLogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        IbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario:", style=wx.ALIGN_CENTER_HORIZONTAL)
        IbUsuario.SetMinSize((445, 20))
        IbUsuario.SetBackgroundColour(wx.Colour(0, 255, 255))
        IbUsuario.SetForegroundColour(wx.Colour(0, 0, 0))
        IbUsuario.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_1.Add(IbUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        IbClave = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contrase�a:", style=wx.ALIGN_CENTER_HORIZONTAL)
        IbClave.SetMinSize((445, 20))
        IbClave.SetBackgroundColour(wx.Colour(0, 255, 255))
        IbClave.SetForegroundColour(wx.Colour(0, 0, 0))
        IbClave.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_1.Add(IbClave, 0, wx.EXPAND, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        self.tfClave.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnEntrar = wx.Button(self.panel_1, wx.ID_ANY, "Entrar")
        self.btnEntrar.SetMinSize((120, 35))
        self.btnEntrar.SetBackgroundColour(wx.Colour(0, 127, 255))
        self.btnEntrar.SetForegroundColour(wx.Colour(0, 0, 0))
        self.btnEntrar.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.btnEntrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        self.btnSalir.SetMinSize((120, 35))
        self.btnSalir.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btnSalir.SetForegroundColour(wx.Colour(0, 0, 0))
        self.btnSalir.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnEntrar.Bind(wx.EVT_BUTTON, self.confirmar_ususario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_ususario_clave(self, event):  # wxGlade: Ventana1.<event_handler>
        print("Event handler 'confirmar_ususario_clave' not implemented!")
        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: Ventana1.<event_handler>
        print("Event handler 'cerrar_programa' not implemented!")
        event.Skip()

# end of class Ventana1

class MyAppCineplus(wx.App):
    def OnInit(self):
        self.frame = Ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyAppCineplus

if __name__ == "__main__":
    appCineplus = MyAppCineplus(0)
    appCineplus.MainLoop()
