#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Sat Nov 22 13:15:01 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((454, 461))
        self.SetTitle("inicio de sesion-CinePlus")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("Logotipo.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(10, 79, 255))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        lbTitulo = wx.StaticText(self.panel_1, wx.ID_ANY, "Bienvenido(a) a CinePlus", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbTitulo.SetMinSize((132, 35))
        lbTitulo.SetForegroundColour(wx.Colour(0, 0, 0))
        lbTitulo.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbTitulo, 0, wx.EXPAND, 0)

        lbLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("Logotipo.jpg", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(lbLogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbUsuario.SetMinSize((445, 20))
        lbUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbClave = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contraseña:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbClave.SetMinSize((445, 20))
        lbClave.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(lbClave, 0, 0, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        self.tfClave.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnEntrar = wx.Button(self.panel_1, wx.ID_ANY, "Entrar")
        self.btnEntrar.SetMinSize((120, 35))
        self.btnEntrar.SetBackgroundColour(wx.Colour(29, 236, 37))
        self.btnEntrar.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.btnEntrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "Salir")
        self.btnSalir.SetMinSize((120, 35))
        self.btnSalir.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btnSalir.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnEntrar.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: ventana1.<event_handler>
        nombre = self.tfUsuario.GetValue ()
        clave = self.tfClave.GetValue ()

        if nombre == "Jeraldine" and clave == "123":
            print(f"¡Bienvenida, {nombre}!Acceso autorizado.")
            v2 = ventana2(self)
            v2.Show()
            self.Hide()

        else:
            print("Acceso denegado. Usuario o clave incorrectos.")

        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: ventana1.<event_handler>
        pregunta = wx.MessageDialog (self, "se cerrara la ventana.\n"\
        "Estas seguro que deseas salir?", "Confirmar salida",style= wx.YES_NO | wx.ICON_QUESTION)

        respuesta = pregunta.ShowModal()
        pregunta.Destroy()

        if respuesta ==wx.ID_YES:
            print("Bye")
            self.Close()
        event.Skip()

# end of class ventana1

class ventana2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((482, 507))
        self.SetTitle("Taquilla-CinePlus-")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("taquillas.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(226, 53, 255))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("taquillas.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Taquilla")
        label_1.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("taquillas.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_3 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Película:")
        label_2.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_2, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        label_3.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_3, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        label_4.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_3.Add(label_4, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_2.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.cmbPelicula = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Megan 2.0", u"Mufasa:El rey león", "Las guerreras K-pop"], style=wx.CB_DROPDOWN)
        self.cmbPelicula.SetMinSize((120, 30))
        grid_sizer_4.Add(self.cmbPelicula, 0, 0, 0)

        self.lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "----")
        self.lbSala.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_4.Add(self.lbSala, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_5.Add(self.rbHorario1, 0, 0, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_5.Add(self.rbHorario2, 0, 0, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_5.Add(self.rbHorario3, 0, 0, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_5.Add(self.panel_2, 1, wx.EXPAND, 0)

        self.bmPelicula = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:\\CineplusJeraldine3A\\Pelicula2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(self.bmPelicula, 0, wx.ALIGN_RIGHT, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos")
        label_6.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(label_6, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        grid_sizer_6 = wx.GridSizer(2, 2, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos $(80):")
        label_7.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_6.Add(label_7, 0, 0, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "",style=wx.TE_PROCESS_ENTER)
        self.tfAdultos.SetMinSize((110, 23))
        self.tfAdultos.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_6.Add(self.tfAdultos, 0, 0, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores $ (70):")
        label_8.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_6.Add(label_8, 0, 0, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "",style=wx.TE_PROCESS_ENTER)
        self.tfMenores.SetMinSize((110, 23))
        self.tfMenores.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_6.Add(self.tfMenores, 0, 0, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal: $")
        self.lbSubtotal.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.lbSubtotal, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetMinSize((170, 54))
        self.btnLimpiar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        self.btnLimpiar.SetBitmap(wx.Bitmap("D:\\CineplusJeraldine3A\\limpiarboton.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_7.Add(self.btnLimpiar, 0, 0, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetMinSize((170, 54))
        self.btnSiguiente.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        self.btnSiguiente.SetBitmap(wx.Bitmap("D:\\CineplusJeraldine3A\\siguienteboton.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_7.Add(self.btnSiguiente, 0, wx.ALIGN_RIGHT, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cmbPelicula.Bind(wx.EVT_COMBOBOX, self.seleccionPelicula)
        self.rbHorario1.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario1)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.tfAdultos.Bind(wx.EVT_TEXT_ENTER, self.sumarAdultos)
        self.tfMenores.Bind(wx.EVT_TEXT_ENTER, self.sumarMenores)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        # end wxGlade

    def cargar_imagen(self,ruta):
        bitmap=wx.Bitmap(ruta,wx.BITMAP_TYPE_ANY)
        self.bmPelicula.SetBitmap(bitmap)


    def seleccionPelicula(self, event):  # wxGlade: ventana2.<event_handler>
        pelicula=self.cmbPelicula.GetValue()
        imagen=""
        sala=""
        horario1=horario2=horario3=""
        
        print(f"Pelicula seleccionada: {pelicula}")

        if pelicula == "Mufasa:El rey león":
           imagen="Pelicula1.png"
           sala="1"
           horario1="14:00"
           horario2="17:00"
           horario3="20:00"

        elif pelicula == "Las guerreras K-pop":
            imagen="Pelicula2.png"
            sala="2"
            horario1="13:30"
            horario2="16:30"
            horario3="19:30"
        
        elif pelicula == "Megan 2.0":
            imagen="Pelicula3.png"
            sala="3"
            horario1="15:00"
            horario2="18:00"
            horario3="21:00"

        self.cargar_imagen(imagen)
        self.lbSala.SetLabel(sala)
        self.rbHorario1.SetLabel(horario1)
        self.rbHorario2.SetLabel(horario2)
        self.rbHorario3.SetLabel(horario3)
        self.informacion=f"Pelicula:{pelicula} \n Sala:{sala}"
        print(f"Listo paran disfrutar de \n {self.informacion}")
        event.Skip()

    def seleccionHorario1(self, event):  # wxGlade: ventana2.<event_handler>
        self.horarioSeleccinado=self.rbHorario1.GetLabelText()
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: ventana2.<event_handler>
        self.horarioSeleccinado=self.rbHorario2.GetLabelText()
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: ventana2.<event_handler>
        self.horarioSeleccinado=self.rbHorario3.GetLabelText()
        event.Skip()

    def sumarAdultos(self, event):  # wxGlade: ventana2.<event_handler>
        try:
            self.adultos = int(self.tfAdultos.GetValue())
            subtotal_a = self.adultos * 80
            self.subtotal=subtotal_a
            self.lbSubtotal.SetLabel(f"Subtotal: ${subtotal_a:.2f}")
        except ValueError:
            wx.MessageBox("Por favor ingresa un numero valido", "Error", wx.OK | wx.ICON_ERROR)
        event.Skip()

    def sumarMenores(self, event):  # wxGlade: ventana2.<event_handler>
        try:
            self.menores = int(self.tfMenores.GetValue())
            subtotal_b = self.menores * 70
            self.subtotal=(self.adultos*80) + subtotal_b
            self.lbSubtotal.SetLabel(f"Subtotal: ${self.subtotal:.2f}")
        except ValueError:
            wx.MessageBox("Por favor ingresa un numero valido", "Error", wx.OK | wx.ICON_ERROR)
        event.Skip()

                        #Creacion de la funcion limpiar para la ventana 2
    def limpiarValores_Campos(self):

            #Limpiar Variables de Instancia
            self.subtotal=0
            self.adultos=0
            self.menores=0
            self.informacion=""
            self.horarioSeleccionado=""

            #Limpiar Campos
            self.cargar_imagen("Logotipo.jpg")
            self.rbHorario1.SetLabel("00:00")
            self.rbHorario2.SetLabel("00:00")
            self.rbHorario3.SetLabel("00:00")
            self.rbHorario1.SetValue(False)
            self.rbHorario2.SetValue(False)
            self.rbHorario3.SetValue(False)
            self.cmbPelicula.SetSelection(wx.NOT_FOUND)
            self.lbSala.SetLabel("----")
            self.tfAdultos.SetValue("0")
            self.tfMenores.SetValue("0")
            self.lbSubtotal.SetLabel("0")

    def limpiarTaquilla(self, event):  # wxGlade: ventana2.<event_handler>
        self.limpiarValores_Campos()
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: ventana2.<event_handler>
        self.informacion = f"{self.informacion} \n Horario:{self.horarioSeleccinado}"
        self.informacion = f"{self.informacion} \n Adultos:{self.adultos}\n Menores de 12 años: {self.menores}"
        self.informacion = f"{self.informacion} \n Subtotal:{self.subtotal}"

        pregunta = wx.MessageDialog(
        self,
        f"Confirmacion de Taquilla.\n"
        f"¿Estas seguro que desea adquirir?\n\n{self.informacion}",
        "Taquilla",
        style=wx.YES_NO | wx.ICON_QUESTION
        )

        respuesta = pregunta.ShowModal()
        pregunta.Destroy() #cerramos el dialogo

        if respuesta == wx.ID_YES:
            print (f"Venta de Taquilla realizada\n {self.informacion}")
            v3 = ventana3(self,informacion=self.informacion,subtotal=self.subtotal)
            v3.Show()
            self.limpiarValores_Campos()
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarValores_Campos()
        event.Skip()

# end of class ventana2

class ventana3(wx.Frame):
    def __init__(self, parent, informacion="",subtotal=0):
        # begin wxGlade: ventana3.__init__
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((763, 630))
        self.SetTitle("Dulceria-CINEPLUS-")
        print(f"Datos de la ventana 2:\n Informacion: {informacion} \n")
        print(f"subtotal: {subtotal}")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("dulcerialogo.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(255, 100, 193))

        #variable de instancias ventana 3
        self.infoDulceria =""
        self.subtotalDulceria=0
        self.infoTaquilla=informacion
        self.subtotalTaquilla=subtotal

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("dulcerialogo.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Dulceria")
        label_1.SetFont(wx.Font(20, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("dulcerialogo.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT, 0)

        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        grid_sizer_7 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        self.spComboB = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spComboB.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_7.Add(self.spComboB, 0, 0, 0)

        grid_sizer_8 = wx.GridSizer(2, 1, 0, 0)
        grid_sizer_7.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Basico $75")
        label_2.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_8.Add(label_2, 0, 0, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas Ch\nRefresco Ch")
        label_3.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_8.Add(label_3, 0, 0, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("basico.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_7.Add(bitmap_3, 0, wx.EXPAND, 0)

        grid_sizer_9 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_2.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        self.spComboC = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spComboC.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_9.Add(self.spComboC, 0, 0, 0)

        grid_sizer_10 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_9.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cuates $130")
        label_4.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_10.Add(label_4, 0, 0, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas Md\n2 Refrescos Md")
        label_5.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_10.Add(label_5, 0, 0, 0)

        bitmap_4 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("combo cuates.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_9.Add(bitmap_4, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        grid_sizer_11 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_3.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        self.spComboF = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spComboF.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_11.Add(self.spComboF, 0, 0, 0)

        grid_sizer_12 = wx.FlexGridSizer(2, 1, 0, 0)
        grid_sizer_11.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "Familiar $200")
        label_15.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_12.Add(label_15, 0, 0, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas G\n3 refrescos G\n1 Dulce")
        label_16.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_12.Add(label_16, 0, 0, 0)

        bitmap_7 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("familiar.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_11.Add(bitmap_7, 0, 0, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        grid_sizer_3.Add(self.panel_2, 1, wx.EXPAND, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        grid_sizer_13 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("palomitas.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_13.Add(bitmap_5, 0, 0, 0)

        grid_sizer_14 = wx.FlexGridSizer(4, 1, 0, 0)
        grid_sizer_13.Add(grid_sizer_14, 1, wx.EXPAND, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas")
        label_14.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_14.Add(label_14, 0, 0, 0)

        grid_sizer_15 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_14.Add(grid_sizer_15, 1, wx.EXPAND, 0)

        self.spPalomitasCh = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasCh.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_15.Add(self.spPalomitasCh, 0, 0, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas")
        label_17.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_15.Add(label_17, 0, 0, 0)

        grid_sizer_16 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_14.Add(grid_sizer_16, 1, wx.EXPAND, 0)

        self.spPalomitasMd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasMd.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_16.Add(self.spPalomitasMd, 0, 0, 0)

        label_18 = wx.StaticText(self.panel_1, wx.ID_ANY, "Medianas")
        label_18.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_16.Add(label_18, 0, 0, 0)

        grid_sizer_17 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_14.Add(grid_sizer_17, 1, wx.EXPAND, 0)

        self.spPalomitasG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        self.spPalomitasG.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_17.Add(self.spPalomitasG, 0, 0, 0)

        label_19 = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes")
        label_19.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_17.Add(label_19, 0, 0, 0)

        grid_sizer_18 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_4.Add(grid_sizer_18, 1, wx.EXPAND, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("refrescos.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_18.Add(bitmap_6, 0, 0, 0)

        grid_sizer_19 = wx.FlexGridSizer(3, 1, 0, 0)
        grid_sizer_18.Add(grid_sizer_19, 1, wx.EXPAND, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "Refrescos")
        label_13.SetMinSize((343, 23))
        label_13.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_19.Add(label_13, 0, wx.EXPAND, 0)

        grid_sizer_21 = wx.FlexGridSizer(1, 3, 0, 0)
        grid_sizer_19.Add(grid_sizer_21, 1, wx.EXPAND, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Tamaño")
        label_12.SetMinSize((111, 23))
        label_12.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_21.Add(label_12, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "Sabor")
        label_11.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_21.Add(label_11, 0, wx.ALIGN_RIGHT | wx.EXPAND, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad")
        label_10.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_21.Add(label_10, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_20 = wx.FlexGridSizer(1, 4, 0, 0)
        grid_sizer_19.Add(grid_sizer_20, 1, wx.EXPAND, 0)

        self.cmbTamano = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["CHICOS","MEDIANO","GRANDE"], style=wx.CB_DROPDOWN)
        self.cmbTamano.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_20.Add(self.cmbTamano, 0, 0, 0)

        self.cmbSabor = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["coca cola","sprit","manzanita"], style=wx.CB_DROPDOWN)
        grid_sizer_20.Add(self.cmbSabor, 0, 0, 0)

        self.spCantidad = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_20.Add(self.spCantidad, 0, 0, 0)

        self.btnAgregar = wx.Button(self.panel_1, wx.ID_ANY, "Agregar")
        self.btnAgregar.SetFont(wx.Font(9, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_20.Add(self.btnAgregar, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        grid_sizer_22 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_5.Add(grid_sizer_22, 1, wx.EXPAND, 0)

        label_20 = wx.StaticText(self.panel_1, wx.ID_ANY, "Productos Agregados:")
        label_20.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_22.Add(label_20, 0, 0, 0)

        self.lbProductosAgregados = wx.StaticText(self.panel_1, wx.ID_ANY, "---")
        self.lbProductosAgregados.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        grid_sizer_22.Add(self.lbProductosAgregados, 0, 0, 0)

        grid_sizer_23 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_5.Add(grid_sizer_23, 1, wx.EXPAND, 0)

        label_22 = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal Dulceria")
        label_22.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_23.Add(label_22, 0, 0, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "$00.00")
        self.lbSubtotal.SetForegroundColour(wx.Colour(255, 0, 0))
        self.lbSubtotal.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_23.Add(self.lbSubtotal, 0, 0, 0)

        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar")
        self.btnLimpiar.SetBitmap(wx.Bitmap("limpiarboton.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_6.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente")
        self.btnSiguiente.SetBitmap(wx.Bitmap("siguienteboton.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_6.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER, 0)

        grid_sizer_21.AddGrowableRow(0)
        grid_sizer_21.AddGrowableCol(2)

        grid_sizer_19.AddGrowableCol(0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spComboB.Bind(wx.EVT_SPINCTRL, self.calcularComboBasico)
        self.spComboC.Bind(wx.EVT_SPINCTRL, self.calcularComboCuates)
        self.spComboF.Bind(wx.EVT_SPINCTRL, self.calcularComboFamiliar)
        self.spPalomitasCh.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasCh)
        self.spPalomitasMd.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasMd)
        self.spPalomitasG.Bind(wx.EVT_SPINCTRL, self.calcularPalomitasG)
        self.btnAgregar.Bind(wx.EVT_BUTTON, self.AgregarRefresco)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarDulceria)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteDulceria)
        # end wxGlade

    def calcularComboBasico(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboB.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Basicos \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularComboCuates(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboC.GetValue())
        subtotalcombo=numero*130
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Cuates \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularComboFamiliar(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboF.GetValue())
        subtotalcombo=numero*200
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Familiar \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularPalomitasCh(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spPalomitasCh.GetValue())
        subtotalcombo=numero*25
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas Chicas \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularPalomitasMd(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spPalomitasMd.GetValue())
        subtotalcombo=numero*40
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas Medianas \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularPalomitasG(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spPalomitasG.GetValue())
        subtotalcombo=numero*60
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas Grandes \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def AgregarRefresco(self, event):  # wxGlade: ventana3.<event_handler>
         numero=int(self.spCantidad.GetValue())
         tamanyo=self.cmbTamano.GetValue()
         sabor=self.cmbSabor.GetValue()
         subtotalrefresco=0
         if tamanyo == "CHICO":
             subtotalrefresco=numero*25
         elif tamanyo == "MEDIANO":
             subtotalrefresco=numero*40
         elif tamanyo == "GRANDE":
             subtotalrefresco=numero*60
         self.subtotalDulceria=self.subtotalDulceria+subtotalrefresco
         self.lbProductosAgregados.SetLabel(self.infoDulceria)

         self.infoDulceria=self.infoDulceria + f"{numero} Refresco: {sabor} tamaño {tamanyo}\n"
         self.lbProductosAgregados.SetLabel(self.infoDulceria)
         event.Skip()

    def limpiarDulceria(self):
        self.limpiarDulceria()

    def limpiarDulceria(self, event):  # wxGlade: ventana3.<event_handler>
        #Limpiamos las variables de instancias
        self.subtotalDulceria=0
        self.infoDulceria=""
        self.infoTaquilla
        
        #limpiamos los controles
        self.spComboB.SetValue(0)
        self.spComboC.SetValue(0)
        self.spComboF.SetValue(0)
        self.spPalomitasCh.SetValue(0)
        self.spPalomitasMd.SetValue(0)
        self.spPalomitasG.SetValue(0)
        self.spCantidad.SetValue(0)
        self.cmbSabor.SetSelection(wx.NOT_FOUND)
        self.cmbTamano.SetSelection(wx.NOT_FOUND)
        self.lbProductosAgregados.SetLabel("_ _ _")

        event.Skip()

    def siguienteDulceria(self, event):  # wxGlade: ventana3.<event_handler>
        pregunta = wx.MessageDialog(self,
        f"Confirmacion de Dulceria.\n"
        f"¿Estas seguro que desea adquirir?\n\n{self.infoDulceria}\n"
        "Dulceria",style=wx.YES_NO | wx.ICON_QUESTION)

        respuesta = pregunta.ShowModal ()
        pregunta.Destroy() # Cerramos el dialogo

        if respuesta == wx.ID_YES:
            self.limpiarDulceria
            self.Hide()
            v4 = ventana4(self, informacion=self.infoTaquilla,
                          subtotal1=self.subtotalTaquilla,
                          informacion2=self.infoDulceria,
                          subtotal2=self.subtotalDulceria)
            
            v4.Show()
            self.limpiarDulceria
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarDulceria()
        event.Skip()

# end of class ventana3

class ventana4(wx.Frame):
    def __init__(self, parent, informacion="",subtotal1=0, informacion2="", subtotal2=0):
        # begin wxGlade: ventana4.__init__
        #kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        #wx.Frame.__init__(self, *args, **kwds)
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((427, 448))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(219, 112, 147))
        
        #Variables de Instancias de la ventana4
        self.infoTaquilla=informacion
        self.infoDulceria=informacion2
        self.subtotalTaquilla=subtotal1
        self.subtotalDulceria=subtotal2
        self.total=self.subtotalTaquilla+self.subtotalDulceria
        print(f"------------------Dulceria, {self.infoDulceria}")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(9, 1, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        bitmap_3 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./tickets.png", wx.BITMAP_TYPE_ANY))
        bitmap_3.SetMinSize((135, 82))
        grid_sizer_2.Add(bitmap_3, 0, 0, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "TICKET")
        label_6.SetMinSize((105, 37))
        label_6.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_2.Add(label_6, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./tickets.png", wx.BITMAP_TYPE_ANY))
        bitmap_2.SetMinSize((135, 82))
        grid_sizer_2.Add(bitmap_2, 0, 0, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "TAQUILLA")
        label_7.SetMinSize((125, 47))
        label_7.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(label_7, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoTaquilla}",style=wx.ALIGN_CENTER_HORIZONTAL)
        grid_sizer_1.Add(lbTaquilla, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbSubtotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, f"Subtotal:${self.subtotalTaquilla}")
        lbSubtotalTaquilla.SetBackgroundColour(wx.Colour(219, 112, 147))
        lbSubtotalTaquilla.SetForegroundColour(wx.Colour(39, 39, 160))
        lbSubtotalTaquilla.SetFont(wx.Font(18, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(lbSubtotalTaquilla, 0, 0, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "DULCERIA")
        label_8.SetMinSize((145, 37))
        label_8.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(label_8, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoDulceria}",style=wx.ALIGN_CENTER_HORIZONTAL)
        lbDulceria.SetMinSize((200, 50))
        grid_sizer_1.Add(lbDulceria, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbSubtotalDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"Subtotal:${self.subtotalDulceria}")
        lbSubtotalDulceria.SetForegroundColour(wx.Colour(35, 35, 145))
        lbSubtotalDulceria.SetFont(wx.Font(18, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(lbSubtotalDulceria, 0, 0, 0)

        lbTotal = wx.StaticText(self.panel_1, wx.ID_ANY, f"Total:${self.total}")
        lbTotal.SetMinSize((145, 37))
        lbTotal.SetForegroundColour(wx.Colour(255, 0, 0))
        lbTotal.SetFont(wx.Font(18, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(lbTotal, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "Cancelar\n")
        grid_sizer_3.Add(self.btnCancelar, 0, 0, 0)

        self.btnFinalizar = wx.Button(self.panel_1, wx.ID_ANY, "Finalizar\n")
        grid_sizer_3.Add(self.btnFinalizar, 0, 0, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarVentana)
        self.btnFinalizar.Bind(wx.EVT_BUTTON, self.finalizarVenta)
        # end wxGlade

    def cancelarVentana(self, event):  # wxGlade: ventana4.<event_handler>
        wx.MessageBox("La compra fue cancelada.","Cancelar Ventana",wx.OK | wx.ICON_INFORMATION)
        event.Skip()

    def finalizarVenta(self, event):  # wxGlade: ventana4.<event_handler>
        wx.MessageBox("Compra Finalizada.", "Finalizar Venta", wx.OK | wx.ICON_INFORMATION)
        v2 = ventana2(self)
        v2.Show()
        self.Hide()
        wx.Exit()
        event.Skip()

# end of class ventana4

class MyAppCinePlus(wx.App):
    def OnInit(self):
        self.frame_1 = ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame_1)
        self.frame_1.Show()
        return True

# end of class MyAppCinePlus

if __name__ == "__main__":
    appCinePlus = MyAppCinePlus(0)
    appCinePlus.MainLoop()
